server:
  port: 8763

spring:
  application:
    name: service-lucy

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        
# http://localhost:8762/hystrix
# http://localhost:8762/actuator/hystrix.stream